app/questoes/urls.py
from django.urls import path
from . import views as questoes

app_name = 'questoes'

urlpatterns = [
    path('', questoes.Disciplinas.as_view(), name='disciplinas'),
    path('disciplina/<pk>/detalhes', questoes.DisciplinaDetalhes.as_view(), name='detalhes-disciplina'),
    path('adicionar/questao', questoes.AddQuestao.as_view(), name='add-questao'),
    path('questoes/', questoes.Questoes.as_view(), name='questoes'),
    path('questao/<pk>/detalhes', questoes.QuestaoDetalhes.as_view(), name='detalhes-questao'),
    path('questao/<pk>/excluir', questoes.QuestaoExcluir.as_view(), name='excluir-questao'),
    path('questao/<pk>/editar', questoes.QuestaoEditar.as_view(), name='editar-questao'),
    path('provas/', questoes.Provas.as_view(), name='provas'),
    path('prova/<pk>/detalhes', questoes.ProvaDetalhes.as_view(), name='detalhes-prova'),
]

hub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # core
    path('', include('app.core.urls'), name='core'),
    # questoes
    path('', include('app.questoes.urls'), name='questoes'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/questoes/models.py
from django.db import models
from app.core.models import UUIDUser, CreateUpdateModel

class Disciplina(CreateUpdateModel):
    professor = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='professores', verbose_name='professor')
    nome = models.CharField(max_length=255, verbose_name='nome da disciplina')

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'disciplina'
        verbose_name_plural = 'disciplinas'

class Questao(CreateUpdateModel):
    professor = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='teachers', verbose_name='professor')
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE, related_name='disciplinas', verbose_name='disciplina')
    enunciado = models.TextField(verbose_name='enunciado')
    imagem = models.ImageField(upload_to='images/', verbose_name='imagem da questão', blank=True)
    alternativa_um = models.CharField(max_length=255, verbose_name='1ª alternativa')
    alternativa_dois = models.CharField(max_length=255, verbose_name='2ª alternativa')
    alternativa_tres = models.CharField(max_length=255, verbose_name='3ª alternativa')
    alternativa_quatro = models.CharField(max_length=255, verbose_name='4ª alternativa')
    correta = models.CharField(max_length=255, verbose_name='alternativa correta')

    def __str__(self):
        return self.enunciado

    class Meta:
        verbose_name = 'questão'
        verbose_name_plural = 'questões'

class Prova(CreateUpdateModel):
    professor = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, verbose_name='professor', related_name='prof')
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE, verbose_name='disciplina', related_name='disciplina')
    nome = models.CharField(max_length=255, verbose_name='nome da prova')
    questoes = models.ManyToManyField(Questao, related_name='questions', verbose_name='questões da prova', blank=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'prova'
        verbose_name_plural = 'provas'

app/questoes/forms.py
from django import forms
from .models import Questao

class AddQuestaoForm(forms.ModelForm):
    def save(self, commit = True):
        file = super(AddQuestaoForm, self).save(commit=False)
        if commit:
            file.save()
        return file

    class Meta:
        model = Questao
        fields = ['professor', 'disciplina', 'enunciado', 'imagem', 'alternativa_um', 'alternativa_dois', 'alternativa_tres', 'alternativa_quatro', 'correta']
        labels = {
            'professor': 'Professor(a)',
            'disciplina': 'Disciplina',
            'enunciado': 'Enunciado',
            'imagem': 'Imagem (opcional)',
            'alternativa_um': '1ª Alternativa',
            'alternativa_dois': '2ª Alternativa',
            'alternativa_tres': '3ª Alternativa',
            'alternativa_quatro': '4ª Alternativa',
            'correta': 'Alternativa Correta',
        }
        widgets = {
            'imagem': forms.FileInput()
        }

app/questoes/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Disciplina, Questao, Prova
from .forms import AddQuestaoForm
from django.urls import reverse_lazy

class Disciplinas(LoginRequiredMixin, View):
    def get(self, request):
        disciplinas = Disciplina.objects.filter(professor = self.request.user).order_by('nome')
        return render(request, 'questoes/disciplinas.html', {'disciplinas': disciplinas})

    def post(self, request):
        disciplina = Disciplina(professor=self.request.user, nome=request.POST.get('nome'))
        disciplina.save()
        return redirect('questoes:disciplinas')

class DisciplinaDetalhes(View):
    def get(self, request, pk):
        questoes = Questao.objects.filter(disciplina = pk)
        disciplina = Disciplina.objects.filter(id = pk).first()
        return render(request, 'questoes/detalhes-disciplina.html', {'questoes': questoes, 'disciplina': disciplina})

    def post(self, request, pk):
        disciplina = Disciplina.objects.filter(id = pk).first()
        prova = Prova(professor=self.request.user, disciplina=disciplina, nome=request.POST.get('nome'))
        prova.save()
        return redirect('questoes:detalhes-disciplina', pk = pk)

class AddQuestao(CreateView):
    model = Questao
    template_name = 'questoes/add-questao.html'
    success_url = reverse_lazy('questoes:disciplinas')
    form_class = AddQuestaoForm

    def get_context_data(self, **kwargs):
        kwargs['disciplinas'] = Disciplina.objects.filter(professor = self.request.user).order_by('nome')
        return super(AddQuestao, self).get_context_data(**kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.save()
        return super(AddQuestao, self).form_valid(form)

class Questoes(View):
    def get(self, request):
        questoes = Questao.objects.filter(professor = self.request.user)
        return render(request, 'questoes/questoes.html', {'questoes': questoes})

class QuestaoDetalhes(View):
    def get(self, request, pk):
        provas = Prova.objects.filter(professor = self.request.user)
        questao = Questao.objects.filter(id = pk).first()
        return render(request, 'questoes/detalhes-questao.html', {'questao': questao, 'provas': provas})

    def post(self, request, pk):
        prova = Prova.objects.filter(id = request.POST.get('prova')).first()
        questao = Questao.objects.filter(id=pk).first()
        prova.questoes.add(questao)
        prova.save()
        return redirect('questoes:detalhes-questao', pk = pk)

class QuestaoExcluir(View):
    def get(self, request, pk):
        questao = Questao.objects.filter(id=pk).first()
        questao.delete()
        return redirect('questoes:disciplinas')

class QuestaoEditar(UpdateView):
    model = Questao
    template_name = 'questoes/update-questao.html'
    success_url = reverse_lazy('questoes:questoes')
    fields = ['enunciado', 'imagem', 'alternativa_um', 'alternativa_dois', 'alternativa_tres', 'alternativa_quatro', 'correta']

class Provas(View):
    def get(self, request):
        provas = Prova.objects.filter(professor = self.request.user)
        return render(request, 'questoes/provas.html', {'provas': provas})

class ProvaDetalhes(View):
    def get(self, request, pk):
        prova = Prova.objects.filter(id = pk).first()
        return render(request, 'questoes/detalhes-prova.html', {'prova': prova})

templates/questoes/add-questao.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Questões
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-plus"></i> Adicionar Questão</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Adicionar Questão</h3>
        </div>
        <div class="box-body">
            <form method="post" action="{% url 'questoes:add-questao' %}">
          {% csrf_token %}
            {{ form.as_p }}
            <a class="btn btn-danger" href="{% url 'questoes:disciplinas' %}">Cancelar</a>
            <button type="submit" class="btn btn-success">Adicionar</button>
            </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
{% endblock %}

<div class="form-group">
                <label for="professor">Professor(a)</label>
                <select class="form-control" name="professor" required id="professor">
                    <option value="{{ request.user.pk }}">{{ request.user.first_name }}</option>
                </select>
            </div>
            <div class="form-group">
                <label for="disciplina">Disciplina</label>
                <select class="form-control" name="disciplina" required id="disciplina">
                    {% for disciplina in disciplinas %}
                    <option value="{{ disciplina.pk }}">{{ disciplina.nome }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
              <label for="enunciado">Enunciado</label>
              <textarea class="form-control" id="enunciado" rows="3" name="enunciado"></textarea>
            </div>
            <div class="form-group">
                <label for="imagem">Imagem (opcional)</label>
                <input type="file" class="form-control-file" id="imagem" name="imagem" accept="image/*">
            </div>
            <div class="form-group">
                <label for="alternativa1">1ª Alternativa</label>
                <input type="text" class="form-control" id="alternativa1" name="alternativa_um" maxlength="255">
            </div>
            <div class="form-group">
                <label for="alternativa2">2ª Alternativa</label>
                <input type="text" class="form-control" id="alternativa2" name="alternativa_dois" maxlength="255">
            </div>
            <div class="form-group">
                <label for="alternativa3">3ª Alternativa</label>
                <input type="text" class="form-control" id="alternativa3" name="alternativa_tres" maxlength="255">
            </div>
            <div class="form-group">
                <label for="alternativa4">4ª Alternativa</label>
                <input type="text" class="form-control" id="alternativa4" name="alternativa_quatro" maxlength="255">
            </div>
            <div class="form-group">
                <label for="correta">Alternativa Correta</label>
                <input type="text" class="form-control" id="correta" name="correta" maxlength="255">
            </div>

templates/questoes/detalhes-disciplina.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Disciplina
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-brain"></i> Detalhes da Disciplina</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Detalhes da Disciplina</h3>
        </div>
        <div class="box-body">
            <!-- Button modal add disciplina -->
            <div style="float: right">
                <a class="btn btn-primary" href="{% url 'questoes:add-questao' %}">
                    Adicionar Questão
                </a>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#provaModal">
                  Criar Prova da Disciplina
                </button>
            </div>
            {% if questoes|length != 0 %}

            <div style="text-align: center; margin-top: 5%;">
                <h3>Questões da Disciplina ({{ disciplina.nome }})</h3>
            </div>
            <table class="table" style="margin-top: 2%;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Enunciado</th>
                  <th scope="col">Imagem</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>
              {% for questao in questoes %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ questao.enunciado }}</td>
                  <td>{% if questao.imagem %}Sim{% else %}Não{% endif %}</td>
                  <td><a href="{% url 'questoes:detalhes-questao' questao.pk %}">Ver Questão</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            {% else %}
            <div style="text-align: center; margin-top: 5%;">
                <h3>O usuário não cadastrou questões para essa disciplina!</h3>
            </div>
            {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

<!-- Modal -->
<div class="modal fade" id="provaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Criar Prova</h5>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'questoes:detalhes-disciplina' disciplina.pk %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="nome">Nome da Prova</label>
            <input type="text" class="form-control" id="nome" placeholder="Prova de Biologia 1º Bimestre" name="nome">
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-success">Criar</button>
      </div>
        </form>
    </div>
  </div>
</div>

{% endblock %}

templates/questoes/detalhes-prova.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Provas
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-brain"></i> Detalhes da Prova</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Detalhes da Prova</h3>
        </div>
        <div class="box-body">
            {% if prova.questoes.all|length != 0 %}
            <div style="text-align: center; margin-top: 5%;">
                <h3>Questões da Prova ({{ prova.nome }})</h3>
            </div>
            <table class="table" style="margin-top: 2%;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Enunciado</th>
                  <th scope="col">Imagem</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>
              {% for questao in prova.questoes.all %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ questao.enunciado }}</td>
                  <td>{% if questao.imagem %}Sim{% else %}Não{% endif %}</td>
                  <td><a href="{% url 'questoes:detalhes-questao' questao.pk %}">Ver Questão</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            {% else %}
            <div style="text-align: center; margin-top: 5%;">
                <h3>O usuário ainda não cadastrou questões para essa prova!</h3>
            </div>
            {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
{% endblock %}

templates/questoes/detalhes-questao.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Questões
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-brain"></i> Detalhes da Questão</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Detalhes da Questão</h3>
        </div>
        <div class="box-body">
            <!-- Button modal add disciplina -->
            <div style="float: right">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#provaModal">
                  Adicionar Questão a Prova
                </button>
                <a class="btn btn-primary" href="{% url 'questoes:editar-questao' questao.pk %}">
                    Editar Questão
                </a>
                <a class="btn btn-danger" href="{% url 'questoes:excluir-questao' questao.pk %}">
                    Excluir Questão
                </a>
            </div>
            <div style="text-align: center; margin-top: 5%;">
                <h3>Questão da Disciplina {{ questao.disciplina }}</h3>
            </div>
            <div style="margin-top: 2%;">
              <div style="margin-top: 2%;">
                  <p style="text-align: justify;">{{ questao.enunciado }}</p>
              </div>
              {% if questao.imagem %}
              <div style="margin-top: 3%; text-align: center;">
                  <img src="/media/{{ questao.imagem }}">
              </div>
              {% endif %}
              <div style="margin-top: 3%;">
                  <p><b>a)</b> {{ questao.alternativa_um }}</p>
                  <p><b>b)</b> {{ questao.alternativa_dois }}</p>
                  <p><b>c)</b> {{ questao.alternativa_tres }}</p>
                  <p><b>d)</b> {{ questao.alternativa_quatro }}</p>
                  <p><b>e)</b> {{ questao.correta }}</p>
              </div>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

<!-- Modal -->
<div class="modal fade" id="provaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Adicionar Questão a Prova</h5>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'questoes:detalhes-questao' questao.pk %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="prova">Escolha a Prova que Deseja Adicinar a Questão</label>
            <select name="prova" id="prova" class="form-control">
                {% for prova in provas %}
                <option value="{{ prova.pk }}">{{ prova.nome }}</option>
                {% endfor %}
            </select>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-success">Criar</button>
      </div>
        </form>
    </div>
  </div>
</div>

{% endblock %}

templates/questoes/disciplinas.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Disciplinas
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-brain"></i> Disciplinas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Lista de Disciplinas</h3>
        </div>
        <div class="box-body">
            <!-- Button modal add disciplina -->
            <div style="float: right">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#disciplinaModal">
                    Adicionar Disciplina
                </button>
            </div>
            {% if disciplinas|length != 0 %}
            <table class="table" style="margin-top: 5%;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>
              {% for disciplina in disciplinas %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ disciplina.nome }}</td>
                  <td><a href="{% url 'questoes:detalhes-disciplina' disciplina.pk %}">Ver Disciplina</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            {% else %}
            <div style="text-align: center; margin-top: 5%;">
                <h3>O usuário não tem disciplinas cadastradas!</h3>
            </div>
            {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

<!-- Modal add Disciplina -->
<div class="modal fade" id="disciplinaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Adicionar Disciplina</h3>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'questoes:disciplinas' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="nome">Nome da Disciplina</label>
            <input type="text" class="form-control" id="nome" placeholder="Matemática" name="nome">
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-success">Adicionar</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/questoes/provas.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Provas
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-file"></i> Provas</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Lista de Provas</h3>
        </div>
        <div class="box-body">
            {% if provas|length != 0 %}
            <table class="table" style="margin-top: 5%;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome da Prova</th>
                  <th scope="col">Quantidade de Questões</th>
                  <th scope="col">Disciplina</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>
              {% for prova in provas %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ prova.nome }}</td>
                  <td>{{ prova.questoes.all|length }}</td>
                  <td>{{ prova.disciplina }}</td>
                  <td><a href="{% url 'questoes:detalhes-prova' prova.pk %}">Ver Prova</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            {% else %}
            <div style="text-align: center; margin-top: 5%;">
                <h3>O usuário ainda não criou provas!</h3>
            </div>
            {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}

templates/questoes/questoes.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Questões
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-question"></i> Questões</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Lista de Questões</h3>
        </div>
        <div class="box-body">
            <div style="float: right">
                <a class="btn btn-primary" href="{% url 'questoes:add-questao' %}">
                    Adicionar Questão
                </a>
            </div>
            {% if questoes|length != 0 %}
            <table class="table" style="margin-top: 5%;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Enunciado</th>
                  <th scope="col">Imagem</th>
                  <th scope="col">Disciplina</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>
              {% for questao in questoes %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ questao.enunciado }}</td>
                  <td>{% if questao.imagem %}Sim{% else %}Não{% endif %}</td>
                  <td>{{ questao.disciplina }}</td>
                  <td><a href="{% url 'questoes:detalhes-questao' questao.pk %}">Ver Questão</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            {% else %}
            <div style="text-align: center; margin-top: 5%;">
                <h3>O usuário ainda não cadastrou questões!</h3>
            </div>
            {% endif %}
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}

templates/questoes/update-questao.html
{% extends '../base.html' %}

{% block content %}

    <section class="content-header">
      <h1>
        Questões
      </h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fas fa-plus"></i> Atualizar Questão</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Atualizar Questão</h3>
        </div>
        <div class="box-body">
            <form method="post">
          {% csrf_token %}
            {{ form.as_p }}
            <a class="btn btn-danger" href="{% url 'questoes:disciplinas' %}">Cancelar</a>
            <button type="submit" class="btn btn-success">Atualizar</button>
            </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
{% endblock %}